### ISSUE TITLE
Slack BOT: добавить команду /add_me для добавления в канал

### ISSUE THREAD

**Issue by vovachebr** [vovachebr/schedule-bot-api#5]
## Как должно работать?

Студент пишет боту `/add_me _название_группы_` и бот добавляет студента в соответствующий закрытый канал.

## Что делать?

* Прочитать, как добавить боту команду
* Вызвать [Slack метод добавления пользователя в канал](https://api.slack.com/methods/channels.invite). Если непонятно, как, создать PR без вызова + новую задачу на его добавление

Если нужно добавить новый путь в api, то изучить, [как добавить новый путь в express](http://expressjs.com/en/guide/routing.html) и добавить его в модуль `routes/index.js`.

**Comment by nlopin** [comment]
@vovachebr дополни, я не уверен в параметрах

**Comment by vovachebr** [comment]
Реализовано в https://github.com/vovachebr/schedule-bot-api/commit/18fb2896ff359972f7979f7c4ee783bd74ae6214
