### ISSUE TITLE
Slack Bot: Добавить команду для получения ближайшего занятия группы

### ISSUE THREAD

**Issue by vovachebr** [vovachebr/schedule-bot-api#7]
Нужно научить Слак бота отвечать на команду `/when_next _номер_группы_` и возвращать информацию о следующем зантяии

## Что делать? 

Прочитать Slack API, разобраться, как добавлять команды боту. 
Если нужно, прочитать, [как добавить новый путь в express](http://expressjs.com/en/guide/routing.html) и добавить его в модуль `lessons`.

**Comment by nlopin** [comment]
@vovachebr что такое последнее занятие? нужно или фильтровать по группе? как будет использоваться этот эндпоинт?

**Comment by vovachebr** [comment]
Последнее занятие, это ближайшее по плану. Тоесть то, которое должно быть в скором времени. Фильтровать по группе конечно же надо будет. У каждой группы будет своё ближайшее занятие. У бота в слаке будет команда для получения ближайшего занятия. Эта команда должна вызывать этот эндпойнт.
Вот тут сделал для телеграмма: https://github.com/vovachebr/schedule-bot-api/commit/47102d06786a0afa39eea6314433a646285741d1
